### ISSUE TITLE
GA launch checklist

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#2120]
We have a GitHub milestone with many items in it at the moment; creating this bug to track top-level features and capabilities we think are needed to make Ground available to any users. Without going into excessive detail:

**P0 - Must have**

- [x] "Public unlisted" surveys, possibly discoverable by URL, QR code, or possibly unique code
- [ ] Cost controls - limits to amount data and traffic
- [x] Prevent invalid polygons (better UI feedback and validation)

**P1 - Should have (or fast follow)**

- [ ] Basic questions when creating survey for metrics (sector, vertical, use, impact, etc)
- [ ] Remove passlist altogether - all users can access
- [ ] Takeout - ability to download survey definition, data, and photos in bulk

**P2 - Nice to have**

- [ ] Require sign-up only for survey creation.
- [ ] Survey templates
- [x] Simplified data collection entry point
- [ ] User-defined geometry type for sites (point or polygon)
- [ ] Simplified job types (predefined xor free form)

@lecrabe @kenstershiro @jo-spek @jabramowitz5 Wdyt?

**Comment by gino-m** [comment]
@shobhitagarwal1612 Also recommends these as P0:

- [ ] Adding basic metrics + altering to ensure Android app quality, for example latency of page loads, map jankiness. Ideally there would be a full-time person who would be notified and responsible for fixing.
- [ ] Privacy and security audit.

@gino-m also:

- [ ] Tracking potential data loss as top priority.

**Comment by kenstershiro** [comment]
@gino-m thanks for this, would be good to discuss the list in tomorrow's PM/UX monthly. Another potential P1 I don't see is  

-  #2013

**Comment by jabramowitz5** [comment]
I think the "public unlisted" surveys is key for general availability. It can help a lot with adding many data collectors to surveys rather than requiring the survey organizer to add each (currently done one email address at a time - #2069), but I think the survey organizer should have some sort of an option to approve them before they get access. Perhaps something important to go along with this would be the email notification that the user has been granted access to the survey (similar to #2077).

Just wanted to flag those two issues that I think would be tied to the "public unlisted" surveys functioning smoothly

**Comment by gino-m** [comment]
Thanks @jabramowitz5. CAN "Share by link" could also be implemented without "Request access" as a first step? If the survey is unlisted, the only way a user could get the URL is by someone sharing the link or QR code with them. In that case, how likely would it be that unauthorized users would get access?

**Comment by jabramowitz5** [comment]
Good point - I think it can go ahead without the "request access" step. I suppose survey organizers could share link/QR code with group of users and then those users could share it further and it could get out of the initial pool of users the organizers intended so "request access" would allow some check on this spread), but that may be an unlikely situation.

**Comment by gino-m** [comment]
@kenstershiro Created/updated individual issues tagged with the appropriate milestone, closing.
